Feat/use location sensor
swent-t16/Voyageur pull request #117
Opened 2024-11-08 13:34 UTC by g0g05arui

## Summary

Use the location (GPS) sensor to automatically center the map view on the user location.
*Note: keep in mind that the emulators are in `Palo Alto` so don't be surprised that it will show up instead of `Lausanne`, if you want you can mock the GPS data yourself in the emulator settings.

A marker will be displayed for the user location. Right now it is just like the others but we shall change that in the future after we added all the necessary functionality.

## Changes
- **Screens/UI:** Search screen will now have a pop-up when you enter the places tab to ask for the location if it wasn't granted previously.

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [x] This PR resolves #116 
- [ ] Tests have been added for new functionality.

##  Testing
- **Manual Testing:**
    - [x] Tested on emulator / physical device.
- **Unit Tests**
    - [ ] Added units tests for this

## Screenshots (if applicable)

<img width="227" alt="image" src="https://github.com/user-attachments/assets/87da96ba-bbb0-4e0f-8a57-3beb31d9e429">
<img width="227" alt="image" src="https://github.com/user-attachments/assets/e985073d-3468-4c1a-95f9-06de59050f72">

@apana03 I am in the middle of adding unit tests for this, but for now the code can be reviewed as is

2024-11-08 15:23 UTC, g0g05arui commented
@apana03 Code tests for this are hard, because google doesnt allow us to add test tags / modifiers for the markers and also the permission request for location can't be mocked so I disabled it for the tests and used a default location

2024-11-09 12:20 UTC, apana03 requested changes

2024-11-09 13:43 UTC, g0g05arui commented
@apana03 I addressed your comments and also added a loader (progress spinner) for the first time the user opens the application and the location needs to be fetched.

2024-11-09 14:36 UTC, apana03 approved these changes
Nice work! Approved :)

2024-11-09 14:43 UTC, merged