[DRAFT] Offline mode
swent-t16/Voyageur pull request #228
Opened 2024-11-27 12:24 UTC by g0g05arui

## Summary

Provide a concise description of the changes proposed in this pull request.
Mention if it's a new feature, bug fix, or refactor, and give a high-level summary.

## Changes

- **Models:** Add details of any new or modified data models.
- **Screens/UI:** Detail the changes to UI components or layouts.
- **Logic/Controllers:** Mention any updates to business logic or controller classes.
- **Repositories:** If any repository classes were added or modified, include details here.
- **Bug Fixes/Improvements:** List any GitHub issues this PR addresses or any improvements to the existing codebase.

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [ ] This PR resolves #`<issue number>` (if applicable).
- [ ] Tests have been added for new functionality.
- [ ] Screenshots or UI changes have been attached (if applicable).
- [ ] Documentation has been updated (if applicable).

##  Testing

Explain how this feature was tested and what kind of testing (unit, integration, UI) has been done. Mention platforms or configurations used for testing.
- **Manual Testing:**
    - [ ] Tested on emulator / physical device.
- **Unit Tests**
    - [ ] Added units tests for this

If you haven't added tests, please create a new issue and assign it.

##  Related Issues/Tickets

List any GitHub issues or tickets related to this PR, using closing keywords to link issues (e.g., Closes #123).

## Screenshots (if applicable)

Attach screenshots or screen recordings that show UI changes.

## 💡 Additional Context

Add any other context or details you think reviewers should know about.

2024-11-27 14:22 UTC, g0g05arui commented
There are still 1 or 2 things that need to be updated (on the activity side, not for trips), e.g. disable the add activity / edit / delete button / the settings tab (on the trip view), but I will create another PR / issues for those as this PR is already quite large

2024-11-28 11:49 UTC, 1andreea26 commented on app/src/main/java/com/android/voyageur/MainActivity.kt
> +                        "No internet connection",
I think here it would be better to replace the string text with a string resource :)

2024-11-28 11:50 UTC, 1andreea26 commented on app/src/main/java/com/android/voyageur/model/user/UserViewModel.kt
> +            Log.d("HELLO", "HELLO COX" + "${_notificationCount.value}")
Here could you remove the unnecessary logs to improve readability?

2024-11-28 12:08 UTC, 1andreea26 commented on app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
> +        // if the device is not conencted to internet show a text
Here I see you added this comment, but you don't show a text here? I see you show one above, is this what you meant?

2024-11-28 12:09 UTC, 1andreea26 commented on app/src/main/java/com/android/voyageur/ui/components/UserProfileContent.kt
> +                enabled = isConnected, // Allow the button to be clickable in all states
Here when you change something, could you please either update or remove the old comments? It becomes confusing otherwise.

2024-11-28 12:14 UTC, 1andreea26 commented on app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt
> +              enabled = isConnected, // Allow the button to be clickable in all states
Same here with this comment.

2024-11-28 12:21 UTC, 1andreea26 requested changes
Great work! Offline mode works very well, and there's some other fixes which improve our app overall! I just left some comments about some logs and comments left behind. Would be great if you could change those.

2024-11-28 12:35 UTC, g0g05arui commented
@1andreea26 Thanks for the review, I updated the changes you request! Please take a look again
Also in this PR I solved a flicker issue in the app, forgot to mention this in the description before.

2024-11-28 12:40 UTC, 1andreea26 approved these changes
Thanks for making the changes quickly! Also, thanks for also mentioning why the code doesn't reach line coverage in the PR description, makes sense! I will approve this! Good job.

2024-11-28 12:59 UTC, merged