add backend support for notifications
swent-t16/Voyageur pull request #239
Opened 2024-11-28 18:27 UTC by BogdanCDev

## Summary

This pull request introduces a new feature that adds backend support for notifications in the Voyageur Android app. Specifically, it implements notification functionality to alert users when there is no internet connection, enhancing user experience and engagement.

## Changes

- **Screens/UI:** Updated MainActivity to include logic for triggering notifications based on network connectivity.
- **Logic/Controllers:** 
  - Added methods in MainActivity:
    - createNotificationChannel(): Sets up the notification channel for Android 8.0 and above.
    - showNotification(): Builds and displays the notification when there's no internet connection.
  - Integrated notification triggers using LaunchedEffect in the Compose UI to respond to connectivity changes.

- **Bug Fixes/Improvements:** Improved user feedback by notifying users of network connectivity issues through system notifications.

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [X] This PR resolves #238
- [ ] Tests have been added for new functionality
- [ ] Screenshots or UI changes have been attached
- [ ] Documentation has been updated

##  Testing

- **Manual Testing:**
    - [ ] Tested on emulator / physical device.
- **Unit Tests**
    - [ ] Added units tests for this

##  Related Issues/Tickets

Closes #238 

## Screenshots

<img width="370" alt="Screenshot 2024-11-28 at 19 26 51" src="https://github.com/user-attachments/assets/8cdda1ce-9186-481a-8705-526f150143b3">
<img width="370" alt="Screenshot 2024-11-28 at 19 27 09" src="https://github.com/user-attachments/assets/383d9e5a-1aa1-426d-85e3-7057797b0c52">

2024-11-28 23:02 UTC, apana03 requested changes
Great job implementing this complex issue! Also thank you for the very detailed documentation it was very easy to understand your code and you followed all the relevant best practices. Only had minor comments regarding the code. However I see there is no tests for this PR, they should be added as this is a complex feature and all the cases regarding permissions must be taken into account. If you don't plan to add tests in this PR please open another issue.

2024-11-29 00:39 UTC, BogdanCDev commented on app/src/main/java/com/android/voyageur/ui/notifications/NotificationHelper.kt
> +            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
Thank you for the excellent suggestion! I’ve just implemented the feature to allow the notification priority to be passed as a parameter in showNotification. While the default remains PRIORITY_DEFAULT, this enhancement adds flexibility for use cases requiring higher priority levels, such as PRIORITY_HIGH for critical notifications.

2024-11-29 00:39 UTC, BogdanCDev commented on app/src/main/java/com/android/voyageur/ui/notifications/NotificationHelper.kt
> +      notificationManager.createNotificationChannel(channel)
Great observation! I've added a null check for the NotificationManager instance in createNotificationChannel to ensure it handles unexpected scenarios gracefully and prevents potential crashes. Thanks for pointing it out!

2024-11-29 00:40 UTC, BogdanCDev commented on app/src/main/java/com/android/voyageur/MainActivity.kt
> +                      text = "Please check your network settings.",
Thanks for highlighting that! I've updated the code to replace all hardcoded strings with references to strings.xml to align with best practices and address the feedback from the last sprint!

2024-11-29 00:41 UTC, BogdanCDev commented on app/src/main/java/com/android/voyageur/ui/notifications/NotificationHelper.kt
> +  fun createNotificationChannel(context: Context) {
Thank you so much! I’m glad the separation of concerns is clear. Your feedback is greatly appreciated!

2024-11-30 01:39 UTC, BogdanCDev commented
The line coverage for the new code in the NotificationHelper is above 80%, as confirmed by Jacoco.

However, the modifications to MainActivity are not included in the coverage reported by SonarCloud. I believe this is due to a specific setting in SonarCloud that excludes coverage for this part of the code. Also, while the changes in MainActivity could theoretically be tested, it would be extremely challenging.

If needed, I can investigate further to clarify the SonarCloud configuration or explore potential test solutions.

2024-12-02 10:27 UTC, apana03 approved these changes
Thank you for taking into account the comments! Also nice job figuring out how to test this new feature as it is not trivial :)

2024-12-02 10:30 UTC, merged