test: add tests for AddTrip
swent-t16/Voyageur pull request #48
Opened 2024-10-15 18:58 UTC by mirceagavrizi

## Summary

Added 4 tests for the AddTrip and a setter for the trip type in TripsViewModel 

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [x] This PR resolves #47 
- [x] Tests have been added for new functionality.
- [ ] Screenshots or UI changes have been attached (if applicable).
- [ ] Documentation has been updated (if applicable).

##  Testing

- **Manual Testing:**
    - [ ] Tested on emulator / physical device.
- **Unit Tests**
    - [x] Added units tests for this

If you haven't added tests, please create a new issue and assign it.

##  Related Issues/Tickets

Closes #47

2024-10-15 21:35 UTC, apana03 commented
Please make sure to reach 80 % code coverage

2024-10-16 11:12 UTC, 1andreea26 commented on app/src/androidTest/java/com/android/voyageur/ui/overview/AddTripTest.kt
> +
Here you could also add a test to check that the user can't submit with an empty name for the trip.

2024-10-16 11:13 UTC, 1andreea26 commented on app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
>                    enabled = name.isNotBlank() && startDate.isNotBlank() && endDate.isNotBlank(),
I think you should also add a Toast requesting the user to enter a name for the trip in case they leave it empty (like in the bootcamp).

2024-10-16 11:16 UTC, 1andreea26 commented on app/src/androidTest/java/com/android/voyageur/ui/overview/AddTripTest.kt
> +}
I checked out the code coverage report and noticed the timestamp is directly converted in the AddTripScreen. I would suggest making a separate method to convert the timestamp, and then writing a test for that method. Or at least writing a test which checks that the timestamp is correctly converted.

2024-10-16 11:19 UTC, 1andreea26 requested changes
The tests look great, but please check out the suggestions to improve code coverage :)

2024-10-17 16:44 UTC, apana03 approved these changes
No major comments, only a code refactoring one. Congrats!

2024-10-17 16:47 UTC, apana03 approved these changes

2024-10-17 16:53 UTC, 1andreea26 approved these changes
The new tests are great. I will approve :).

2024-10-17 16:57 UTC, merged